# Generated by Django 5.2 on 2025-04-27 18:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("excel_files", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DataRow",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("row_index", models.IntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="DataCell",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("string_value", models.TextField(blank=True, null=True)),
                ("integer_value", models.IntegerField(blank=True, null=True)),
                ("float_value", models.FloatField(blank=True, null=True)),
                ("date_value", models.DateField(blank=True, null=True)),
                ("datetime_value", models.DateTimeField(blank=True, null=True)),
                ("boolean_value", models.BooleanField(blank=True, null=True)),
                (
                    "column_definition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="excel_files.columndefinition",
                    ),
                ),
                (
                    "row",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cells",
                        to="data_models.datarow",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DataTable",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("table_name", models.CharField(max_length=255, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("row_count", models.IntegerField(default=0)),
                (
                    "sheet",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="data_table",
                        to="excel_files.excelsheet",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="datarow",
            name="table",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="rows",
                to="data_models.datatable",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="datarow",
            unique_together={("table", "row_index")},
        ),
    ]
