# Generated by Django 5.2 on 2025-04-27 22:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data_models", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TableExport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file", models.FileField(upload_to="exports/")),
                (
                    "format",
                    models.CharField(
                        choices=[
                            ("parquet", "Parquet"),
                            ("csv", "CSV"),
                            ("excel", "Excel"),
                            ("json", "JSON"),
                        ],
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("file_size", models.BigIntegerField(default=0)),
                (
                    "table",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exports",
                        to="data_models.datatable",
                    ),
                ),
            ],
        ),
    ]
